spring.application.name=Blackjack-Backend
spring.datasource.url=jdbc:mysql://monorail.proxy.rlwy.net:23874/railway
spring.datasource.username=root
spring.datasource.password=htXRKPWyCKzExcsDjqMlVLeFTlBQKpdm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none